apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: istio-tls
  namespace: default
spec:
  provider: azure
  secretObjects:                               
  - secretName: istio-ingress-tls
    type: kubernetes.io/tls
    data: 
    - objectName: wildcard-bjdazure-tech
      key: tls.key
    - objectName: wildcard-bjdazure-tech
      key: tls.crt
  parameters:
    usePodIdentity: "true"                                        
    keyvaultName: e616aq-kv                                            
    objects:  |
      array:
        - |
          objectName: wildcard-bjdazure-tech
          objectType: secret
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-bjdazure-tech-gw
  namespace: default
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.bjdazure.tech"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingress-tls
    hosts:
    - "*.bjdazure.tech"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name:  default-bjdazure-tech-vs
  namespace: default
spec:
  hosts:
  -  istio-default.bjdazure.tech
  gateways:
  -  default-bjdazure-tech-gw
  http:
  - route:
    - destination:
        host: ingress-ee85e06-svc
        port:
          number: 80
  
